name: NPM Publish

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm ci
          npm run build --if-present

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
      - run: |
          npm run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.node_auth_token}}
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.github_token}}
